export const character = {
	"ark_dadi": ["male", "geju", 3, ["ark_yaogun", "ark_fuhuo"], []],


	"ark_sikadi_blue": ["female", "luodedao", 5, ["ark_yuelang"], []],

	//米诺斯
	"ark_duanzuizhe": ["female", "minuosi", 4, ["ark_duanzui", "ark_tianqi"], []],
	//萨尔贡
	"ark_mila": ["female", "saergong", "3/3/1", ["ark_zhubei", "ark_shayou"], []],
	//整合运动
	"ark_alina": ["female", "zhenghe", 3, ["ark_jiesi", "ark_zhihen"], ["des:？"]],
	"ark_aiguozhe": ["male", "zhenghe", 4, ["ark_xingjun", "ark_eming"], ["des:<li>【基础信息】<br>技能设计：小妖辰末<br>角色配音：无<br>称号：<font color=#623128>不败战神</font><br>姓名：爱国者<br><br><li>【能力数据】<br>身份定位：反贼，内奸<br>能力定位：防御、输出<br><br><li>【背景故事】<br></br>&nbsp;&nbsp;&nbsp;&nbsp;博卓卡斯替，感染者游击队“盾”的指挥官，萨卡兹勇士中古老至极的血脉，最后的纯血温迪戈。乌萨斯最壮毅的战争化身，整合运动的脊骨，叶莲娜之父。<br>&nbsp;&nbsp;&nbsp;&nbsp;年久失修的铠甲多处破损，曾经坚锐的巨戟锋蚀刃锈。残酷的命运将他愚弄许久，但爱国者永不动摇，绝不退缩，从不怜悯。他与命运较量许久，他要割开命运的咽喉。<br/><br/><b> <i>“我王...你往何处去？”​</i> </b>"]],
	"ark_fushide": ["male", "zhenghe", 3, ["ark_hanmang", "ark_moyv"], []],
	"ark_shuangxing": ["female", "zhenghe", 4, ["ark_jieshuang", "ark_candong", "ark_chegu"], []],
	"ark_shijunzhe": ["female", "zhenghe", 4, ["ark_wuqi", "ark_wuzhong"], []],
	"ark_meifeisite": ["male", "zhenghe", 4, ["ark_cuihua", "ark_huomu", "ark_mengxiang"], []],
	"ark_gezhe": ["none", "shen", 4, ["ark_cangyin", "ark_hunyin"], ["forbidai", "unseen"]],
	"ark_yisang": ["male", "zhenghe", 4, ['ark_jiaoluo', 'ark_nishen'], []],
	"ark_leide": ["male", "zhenghe", 4, ["ark_mirui", "ark_juexi"], []],
	"ark_jiu": ["female", "zhenghe", 4, ['ark_bingdi', 'ark_lianzhi'], []],
	"ark_talula": ["female", "wusasi", '3/3/1', ["ark_yingliao", "ark_tanhen", "ark_xinghuo"], ['zhu']],
	"ark_suigu": ["male", "zhenghe", 4, ["ark_suiwei", "ark_tongpao"], ["des:<li>【基础信息】<br>技能设计：先负、无冕黎明<br>角色配音：无<br>称号：<font color=#EEAD0E>引恨双生</font><br>姓名：碎骨<br><br><li>【能力数据】<br>身份定位：反贼，内奸<br>能力定位：破核、输出<br><br><li>【背景故事】<br></br>"]],

	//"ark_ling": ["female", "yan", 3, ["diy_gongchou", "ark_youyin", "diy_hanmeng"], []],
	"ark_linyuxia": ["female", "yan", "3/3/1", ["ark_jusha", "ark_miying"], []],
	//"ark_jiurishenhaise": ["female", "shen", 3, ["ark_jiuri"], []],

	"ark_nengtianshi": ["female", "latelan", 4, ["ark_saoshe", "ark_kouban"], []],

	"ark_Niyan": ["female", "zhenghe", "4/4/2", ["ark_zerao", "ark_panlei"], ["des:？"]],

	//深池
	"ark_mandela": ["female", "shenchi", 3, ["ark_guyan", "ark_shihai"], ["des:&nbsp;&nbsp;&nbsp;&nbsp;“深池”的头领，与阿赫茉妮一同前来小丘郡行动，对于“领袖”苇草并非绝对的服从，只是用她作为真正领袖的替代品号召“深池”。极度敌视贵族，以将从贵族们手下受过的屈辱悉数奉还为目的而行动，然而一边对高高在上的贵族和富人咬牙切齿，一边崇拜着“深池”真正的“领袖”。被阿赫茉妮派往通讯基站阻击号角等人，使用源石技艺杀死了大提琴，却因为失去了能替领袖发言的机会而陷入愤怒，并向号角和风笛继续展开更加猛烈的攻击。<br/>&nbsp;&nbsp;&nbsp;&nbsp;拥有着能操控岩石的源石技艺，全力施展时，悬浮于身侧的破碎石砾如风暴般呼啸，作为敌人而言非常的强大与危险。"]],
	"ark_ahemoni": ["female", "shenchi", 3, ["ark_tuishi", "ark_jueshi"], ["des:<li>【基础信息】<br>技能设计：无冕黎明、伶<br>角色配音：无<br>称号：<font color=#10A552>秘焰深隐</font><br>姓名：阿赫茉妮<br><br><li>【能力数据】<br>身份定位：反贼，内奸<br>能力定位：破核、输出<br><br><li>【背景故事】<br></br>"]],
	"ark_muxueshouwei": ["none", "shenchi", 4, [""], ["forbidai", "unseen", "des:&nbsp;&nbsp;&nbsp;&nbsp;深池部队中的特殊法术造物。创造者为头领蔓德拉。据蔓德拉所说，她在郊外的坟墓里学习源石技艺，守墓石像是最初的同伴。石像外形有过多次更迭，最新造型仿自某支血脉古老的萨卡兹。这款石像饱含着蔓德拉对维多利亚的怒火。"]],

	//彩虹六号
	"ark_chariot": ["male", "geju", 4, ["ark_zhongwu", "ark_beiku"], []],
	"ark_flashstrike": ["male", "geju", 4, ["ark_shanxi", "ark_yanyu"], []],
	"ark_ash": ["female", "geju", 4, ["ark_tuji", "ark_gongjian", "ark_jidui"], ["zhu"]],
	"ark_frost": ["female", "geju", 4, ["ark_yingta", "ark_zhuilie"], []],
	//叙拉古
	"ark_beinaerduo": ["male", "xvlagu", 4, ["ark_fankui", "ark_piluan", "ark_langying"], ["zhu"]],
	"ark_aerbeituo": ["male", "xvlagu", 4, ["ark_tiaofei", "ark_jueti", "ark_chaixiao"], ["zhu"]],
	"ark_lapulande": ["female", "xvlagu", 4, ["ark_kuange", "ark_langhun"], []],
	"ark_xixili": ["female", "xvlagu", 4, ["ark_chenyun", "ark_daoshu", "ark_xingshui", "ark_weixia"], ["zhu"]],
	"ark_agenier": ["male", "xvlagu", 4, ["ark_xiaosong", "ark_jingshi"], []],
	"ark_qiaowanna": ["female", "xvlagu", 3, ["ark_zhanhong", "ark_zhuanzhuo"], []],
	"ark_walahe": ["male", "xvlagu", 4, ["ark_renzhe", "ark_wangcong"], []],
	"ark_wen": ["male", "xvlagu", 4, ["ark_qiaomang", "ark_jiusheng"], []],
	"ark_danbulang": ["male", "xvlagu", 4, ["ark_xiongyao", "ark_xiaomo"], []],
	"ark_ziyue": ["female", "xvlagu", 3, ["ark_moyu", "ark_liezhu"], ["hiddenSkill"]],
	//    "ark_":["male","xvlagu",4,["",""],[]],
	"ark_Vigil": ["male", "xvlagu", 4, ["ark_changkui", "ark_jique", "ark_langying", "ark_qitu"], []],
	"ark_dekesasi": ["female", "xvlagu", 4, ["ark_yumu", "ark_fuwang"], ["hiddenSkill"]],

	//东国
	"ark_cuoe": ["female", "dongguo", 3, ["ark_kongming", "ark_zhishui"], ["des:？"]],
	"ark_shuiyue": ["female", "dongguo", 3, ["ark_yixiang", "ark_jinghua"], ["forbidai", "unseen"]],
	//拉特兰
	"ark_feiyameita": ["female", "latelan", 4, ["ark_niyan", "ark_chongran"], []],
	"ark_saixiliya": ["female", "latelan", 2, ["ark_guangying", "ark_shengqi"], []],
	"ark_mositima": ["female", "latelan", 4, ["ark_huanbu", "ark_huangshi"], []],
	"ark_jiaozong": ["male", "latelan", 4, ["ark_wanhe", "ark_zhaosheng", "ark_shengdian"], ["zhu"]],
	//玻利瓦尔
	"ark_longshelan": ["male", "boliwaer", 4, ["ark_liduan"], []],
	//骡的岛
	"ark_doctor": ["male", "luodedao", 4, ["ark_luezhen"], ["des:<li>【基础信息】<br>技能设计：何如<br>角色配音：无<br>称号：<font color=#555760>巴别塔之恶灵</font><br>姓名：博士<br><br><li>【能力数据】<br>身份定位：反贼，忠臣<br>能力定位：控场<br><br><li>【背景故事】<br></br>罗德岛的高层领导，三大创始人之一。作为矿石病治疗与天灾研究方面的顶尖学者，拥有生物学，神经工程学博士等学历。致力于清除矿石病，是罗德岛的中流砥柱之一。虽然本身没有战斗能力，但是拥有极强的指挥能力。曾为巴别塔组织成员，参与过萨卡兹王廷内战，被W称为“巴别塔的恶灵”。巴别塔解体后被凯尔希送往切尔诺伯格的石棺进行休眠。切城事变期间被阿米娅等人唤醒，随后担任了罗德岛的指挥官。"]],
	"ark_midiexiang": ["female", "luodedao", 3, ["ark_chaogan", "ark_ruyuan"], ["des:？"]],
	"ark_kuiying": ["male", "luodedao", 4, ["ark_xueying", "ark_yuezhang"], []],
	"ark_hongdou": ["female", "luodedao", 3, ["ark_jilang", "ark_cangmang"], []],
	"ark_furong": ["female", "luodedao", 3, ["ark_fuchen", "ark_shihua"], ["des:？"]],
	"ark_yanrong": ["female", "luodedao", 3, ["ark_zhijiu", "ark_zhouyu"], []],
	"ark_shierteer": ["female", "luodedao", "3/7", ["ark_ronghe", "ark_canhui"], []],
	"ark_keebo": ["female", "luodedao", 3, ["ark_bairen", "ark_xunmi"], []],
	"ark_huihou": ["female", "luodedao", 3, ["ark_shunfeng", "ark_yuyan"], []],
	"ark_moyao": ["female", "luodedao", 3, ["ark_jinji", "ark_jiafang"], []],
	"ark_kedao": ["female", "luodedao", 4, ["ark_hongyi", "ark_canxiang"], ["forbidai", "unseen"]],
	"ark_baoyu": ["female", "luodedao", 4, ["ark_jingyi", "ark_yumian"], []],
	"ark_hong": ["female", "luodedao", 4, ["ark_cigu", "ark_xueshi"], []],
	"ark_sikadi": ["female", "luodedao", 3, ["ark_shutu", "ark_wuguang", "ark_chaoku"], []],
	"ark_linglan": ["female", "luodedao", 3, ["ark_wuyue", "ark_jiuwei"], []],
	"ark_Amy": ["female", "kazidaier", "3/4", ["ark_yihui", "ark_yingxiao", "ark_chengdao"], ["zhu"]],
	"ark_tiaoxiangshi": ["female", "luodedao", 3, ["ark_mufang", "ark_futiao"], []],
	"ark_meilansha": ["female", "luodedao", 4, ["ark_xiehua"], []],
	"ark_huoshen": ["female", "luodedao", 4, ["ark_jingxie", "ark_jirui"], []],

	"ark_luoxiaohei": ["male", "geju", 3, ["ark_huamao", "ark_yuling"], []],


	//精英干员
	"ark_sharp": ["male", "luodedao", 4, ["ark_lifeng", "ark_liangjian"], []],

	//哥伦比亚
	"ark_zongxia": ["female", "laiyin", 3, ["ark_huihai", "ark_qiji", "ark_tianping"], ["zhu", "des:&nbsp;&nbsp;&nbsp;&nbsp;莱茵生命有限公司（Rhine Lab, LLC.），又称莱茵生命实验室、莱茵生命医学研究所，通称“莱茵生命”，是一家位于哥伦比亚的科技公司，致力于拓展生命科学、化学制造、生物应用等技术领域，也是哥伦比亚重点扶持的科技团体。其研究涵盖诸多方向，其成就涉及医疗、防护、设备研发等多个方面。出于商业目的，莱茵生命会于哥伦比亚各地区进行巡回性质的科学展览，展示其最新的研究成果。然而公司内部仍存在着许多未公开项目，据传闻某些项目甚至有军方资源介入。相关人士猜测，这些机密项目，或与针对生物体的源石实验有关。<br/>&nbsp;&nbsp;&nbsp;&nbsp;作为莱茵生命的最高领袖，时常在发布会与讲座中露面的总辖无疑是一名头脑清晰、嗅觉敏锐、手段高明的政客。但在日常的生活中，主持着构件科的总辖更是一名纯粹的研究者，她致力于一项项具有时代颠覆性的巨大突破，沉迷于让那些曾朦胧扑朔的理论在自己的手中变得清澈明晰。崇高的真理殿堂日渐如繁星般宏伟且璀璨，伦理的枷锁日渐如尘埃般黯淡与渺小。与坚持着固守着“科学研究都该在可控的范围内进行”底线的防卫科主任塞雷娅不同，总辖她并不在乎这世俗所谓的“底线”。她看得更高，更远，有时候，大家会觉得即使是头顶的天空也挡不住她的视线。连在人心之间游走自如的生态科主任缪尔塞斯也不得不承认自己也只能稍微揣摩她的心思：“她注视的地方，恐怕这片大地上所有的人都想象不到。”<br/><br/><b> <i>“只要不妨碍我的研究，那么就没有那么一条线存在。”</i> </b>"]],
	"ark_sly": ["female", "laiyin", 4, ["ark_kezhu", "ark_ninghu", "ark_jitu"], []],
	"ark_yifulite": ["female", "laiyin", 3, ["ark_kuangre", "ark_zhuodi"], []],
	"ark_hemo": ["female", "laiyin", 3, ["ark_yanxue", "ark_penwu"], ["des:？"]],
	"ark_miuersaisi": ["female", "laiyin", 3, ["ark_yinshui", "ark_linlin"], []],
	"ark_paerweisi": ["male", "laiyin", 3, ["ark_fengyuan", "ark_cixin"], []],
	"ark_duoluoxi": ["female", "laiyin", 4, ["ark_qingjie", "ark_changfeng"], []],
	"ark_meier": ["female", "laiyin", "4/4/1", ["ark_qiaogou", "ark_yanli"], []],
	"ark_feierdinan": ["male", "laiyin", "3/4", ["ark_zhuguang", "ark_kuiduo"], []],
	"ark_kafuka": ["female", "laiyin", 4, ["ark_guixi", "ark_guaiqiao"], []],
	"ark_xingji": ["female", "gelunbiya", 3, ["ark_huanyu", "ark_shuoxi"], []],
	"ark_Ptilopsis": ["female", "laiyin", 3, ["ark_weiluo", "ark_wenliu"], []],
	"ark_huoerhaiya": ["female", "gelunbiya", 3, ["ark_Hsuyuan", "ark_xingfeng", "ark_youyao"], []],
	"ark_shan": ["male", "gelunbiya", 4, ["ark_jianpiao", "ark_ruyue"], []],
	//乌萨斯
	"ark_helage": ["male", "wusasi", 4, ["ark_yinjun", "ark_huazhuo", "ark_hanlan"], []],
	"ark_lindong": ["female", "wusasi", 3, ["ark_haoling", "ark_zhanhou", "ark_lingxiu"], ["zhu"]],
	"ark_gumi": ["female", "wusasi", 4, ["ark_yezao", "ark_wenpeng"], []],
	//莱塔尼亚
	"ark_getelude": ["female", "laitaniya", 4, ["ark_baijing", "ark_henjue"], []],
	"ark_kanielian": ["female", "laitaniya", "4/4/1", ['ark_jucheng', 'ark_guzhong'], []],
	"ark_biegele": ["male", "laitaniya", 4, ["ark_qinjuan", "ark_yiche", "ark_xinyi"], ["hiddenSkill",]],

	//卡西米尔
	"ark_YQSlinguang": ["female", "kaximiya", 4, ["ark_poxiao", "ark_qvan", "ark_juyao", "ark_linguang"], ["zhu"]],
	"ark_xiaguang": ["female", "kaximiya", 4, ["ark_jueying", "ark_zhuoli"], []],
	"ark_bianren": ["female", "kaximiya", 4, ["ark_lishen", "ark_yiyao"], []],
	"ark_tuola": ["male", "kaximiya", 4, ["diy_tiantu", "diy_zhuyan"], []],
	"ark_baijin": ["female", "kaximiya", 4, ["ark_wangong", "ark_daigong"], []],
	"ark_yanwei": ["female", "kaximiya", 4, ["ark_chiliu", "ark_yanxin", "ark_hongsong"], ["zhu"]],
	"ark_yezong": ["female", "kaximiya", 4, ["ark_kengqiang", "ark_duanliao"], []],
	"ark_monike": ["female", "kaximiya", 4, ["ark_dingmao", "ark_kezhi"], []],
	"ark_jiemi": ["male", "kaximiya", 4, ["ark_kundou", "ark_zhenji"], []],
	"ark_mading": ["male", "kaximiya", 4, ["ark_chantie", "ark_dingfeng"], []],
	"ark_aoermoYinggela": ["male", "kaximiya", 4, ["ark_lingli", "ark_huaiye"], []],
	"ark_makeweici": ["male", "kaximiya", 4, ["ark_beishi", "ark_duzhi"], []],
	"ark_maiji": ["male", "kaximiya", 4, ["ark_zuohuai", "ark_diexie"], []],
	"ark_tuolanKashi": ["male", "kaximiya", 4, ["ark_xiefu", "ark_renxia"], []],
	"ark_fubaiDiaoling": ["male", "kaximiya", "4/8", ["ark_yunu", "ark_juequ"], []],
	"ark_qiaernei": ["male", "kaximiya", 4, ["ark_quanyao", "ark_futuo"], []],
	"ark_luoyi": ["male", "kaximiya", 4, ["ark_baoshen", "ark_weizu"], []],
	"ark_fugewaerde": ["male", "kaximiya", 4, ["ark_pangong", "ark_zongma"], []],
	"ark_taitesiBaiyang": ["male", "kaximiya", 4, ["ark_fulve", "ark_juzi"], []],
	"ark_yuanya": ["female", "kaximiya", 4, ["ark_susou", "ark_wanyue"], []],
	"ark_mobu": ["male", "kaximiya", 4, ["ark_linglong", "ark_rizhen"], []],
	"ark_maenna": ["male", "kaximiya", 4, ["ark_huanhui", "ark_zhanfeng"], []],
	"ark_huihao": ["female", "kaximiya", 4, ["ark_bingce", "ark_zhiqiang"], []],
	"ark_seqiyake": ["male", "kaximiya", 4, ["ark_shefan", "ark_wengzhou"], []],
	"ark_luosu": ["female", "kaximiya", 4, ["ark_zhisheng", "ark_muqian"], []],
	"ark_Decapolis": ["male", "kaximiya", 4, ["ark_kaikang", "ark_linjue", "ark_tongtu"], []],
	"ark_weiweianna": ["female", "kaximiya", 4, ["ark_mingzhu", "ark_gongguang"], []],
	"ark_kewaer": ["male", "kaximiya", 4, ["ark_cijin", "ark_najia"], []],
	"ark_qiesibo": ["male", "kaximiya", 4, ["ark_xiongche", "ark_juexing"], []],
	"ark_daisite": ["female", "kaximiya", 3, ["ark_fenglue", "ark_jianzhu"], []],

	//维多利亚
	"ark_fengdi": ["female", "weiduoliya", 4, ["ark_pojun", "ark_bitang"], ["des:？"]],
	"ark_Saileach": ["female", "weiduoliya", 3, ["ark_yaozhi", "ark_fengzhi"], []],
	"ark_hanmierdun": ["male", "weiduoliya", 4, ["ark_linli", "ark_zhengguan"], []],
	"ark_gelani": ["female", "weiduoliya", 4, ["ark_siju", "ark_dangguan"], []],
	"ark_chengshan": ["female", "weiduoliya", 4, ["ark_daoliu", "ark_huhua"], []],
	"ark_yeyan": ["female", "weiduoliya", 3, ["ark_muying", "ark_kuiqie"], []],
	"ark_haojiao": ["female", "weiduoliya", "4/4/1", ["ark_xuezhan", "ark_junlie"], []],
	"ark_tianhuo": ["female", "weiduoliya", 3, ["ark_liuzhuo", "ark_yunhuo"], []],
	"ark_weifeng": ["female", "weiduoliya", 3, ["ark_qingwei", "ark_xunming"], []],
	"ark_bolv": ["female", "weiduoliya", 3, ["ark_xuanhe", "ark_duyan"], []],
	//伊比利亚
	"ark_ailini": ["female", "yibiliya", 4, ["ark_liechao", "ark_linfeng"], []],
	"ark_liuming": ["male", "yibiliya", 3, ["ark_weixi", "ark_yeyuan"], []],
	"ark_liuming_σ": ["male", "yibiliya", 4, ["ark_changming", "ark_suyuan"], []],
	"ark_jici": ["male", "yibiliya", 4, ["ark_yuci", "ark_gutu"], []],
	"ark_shenhaise": ["female", "yibiliya", 3, ["ark_mingyuan", "ark_shixian"], []],
	"ark_amaya": ["female", "yibiliya", 3, ["ark_shengjing"], ["unseen", "des:&nbsp;&nbsp;&nbsp;&nbsp;深海教会主教之一，早年幽灵鲨实验的实验员之一和实验记录者，被格兰法洛的教徒称为“先知”，公开身份为翻译家。人性恶论、人性无用论支持者，纯粹向往海嗣的大群“社会结构”。自身已有海嗣化倾向，拥有产生溟痕的源石技艺，在事件中不断地利用诡辩洗脑他人，但未能动摇每一个真正的人。最终被幽灵鲨重伤，见到了屠谕者后，自愿被其吞食。<br/>&nbsp;&nbsp;&nbsp;&nbsp;如今战乱不再，隔阂不再，一颗颗心彼此相连，她们也是第一次并肩沐浴在海岸的夜光之下。<br/>&nbsp;&nbsp;&nbsp;&nbsp;“星空真美啊。”<br/>&nbsp;&nbsp;&nbsp;&nbsp;“真美。”那头墨色的长发仿佛沐浴着星光似的熠熠生辉，皎白的侧脸亦闪烁着喜悦的光芒。<br/>&nbsp;&nbsp;&nbsp;&nbsp;“星星会熄灭吗？”<br/>&nbsp;&nbsp;&nbsp;&nbsp;“会，所有的事物，人、动物、星星、甚至时间，都有终结的那一天。”<br/>&nbsp;&nbsp;&nbsp;&nbsp;“它们不害怕吗？明明那么闪耀过了。”<br/>&nbsp;&nbsp;&nbsp;&nbsp;“正因如此，它们才不害怕啊。”<br/>&nbsp;&nbsp;&nbsp;&nbsp;少女依偎在无声的星空之下，星空美得像是一幅画。<br/><br/><br/><b> <i>你会长出羽翼 拥抱星河万里</i> </b><br/><br/><b> <i>将这世间温柔都尽收眼底</i> </b><br/><br/><b> <i>山河湖海 溪流湍急 不露倦意</i> </b><br/><br/><b> <i>任你如风般自由栖息</i> </b><br/><br/><b> <i>你任岁月更替 拥抱星河万里</i> </b><br/><br/><b> <i>是爱与被爱赋予你的权利</i> </b><br/><br/><b> <i>宇宙万物 盎然春意 人间欢喜</i> </b><br/><br/><b> <i>是我偷偷地为你梦呓</i> </b>"]],
	"ark_shendian": ["female", "yibiliya", 3, ["ark_fumu", "ark_mili"], []],

	//炎国
	"ark_weiyanwu": ["male", "yan", 4, ["ark_baihe", "ark_yuxiao"], ["des:<li>【基础信息】<br>技能设计：无冕黎明<br>角色配音：无<br>称号：<font color=#02F78E>纵横恣肆</font><br>姓名：魏彦吾<br><br><li>【能力数据】<br>身份定位：忠臣，内奸<br>能力定位：输出，限制<br><br><li>【背景故事】<br>龙门执政者，为人睿智有礼，但也擅长谋略，手段强硬，在政治圈中拥有较高人望。依靠独特的外交和商业策略，使龙门这一孤城在处理与各个国家的政治关系中游刃有余，被认为是当代的优秀领袖之一。目前龙门的飞速发展之景象便是最好的印证。<br/>&nbsp;&nbsp;&nbsp;&nbsp;魏彦吾保持着先民的血统，眼神锐利，“和他同处于一个空间都使人感到窒息”。传闻因过去职业原因，身体素质超乎常人。被一众退役影卫尊称为“魏公”，疑似身份为大炎皇族。他是陈和塔露拉的舅舅，也是陈的剑术师父，爱德华的结伴兄弟，东国公主文月的丈夫，“鼠王”的战友。武功相当高深，能仅用手指使出赤霄剑法并以此压制“鼠王”林舸瑞。<br/>&nbsp;&nbsp;&nbsp;&nbsp;外交手腕高明，尤擅明谋。在魏彦吾原本计划的和罗德岛的合作中，第二个条件是在整合运动解决后由罗德岛带走龙门的部分感染者，并由龙门支付地块、研究资料、资金和其他资源。魏彦吾知道这将对整个罗德岛造成严重的影响，但也清楚地预判其不可能拒绝如此丰厚的条件。然而在陈的影响下，他最终改变了想法，决心将感染者也作为龙门不可分割的一部分继续容纳下去。"]],
	"ark_wenyue": ["female", "yan", 4, ["ark_tongxin", "ark_zhuojian"], ["des:&nbsp;&nbsp;&nbsp;&nbsp;龙门执政者魏彦吾的妻子，原东国公主，和魏彦吾一起来到龙门定居。虽然外表优雅柔弱（其实对魏彦吾有相当程度的震慑力），但是其实也拥有强大的源石技艺以及政治手段，行事冷静细腻却也非常拥有远见。对魏彦吾来说既是最爱的人，也是最坚实的支持者和后盾。<br/>&nbsp;&nbsp;&nbsp;&nbsp;虽与魏彦吾成婚多年但膝下无子女，将塔露拉和陈两姐妹当作自己的女儿，称其为“小塔/小陈”。<br/>&nbsp;&nbsp;&nbsp;&nbsp;除去政治家的身份，文月也是一名十分厉害的摩托车车手，被称为“在无人的深夜街道疾驰，闪现在弯道上的幽灵车手”。曾穿着和服使用奢华版水箭35炫彩机车与星熊飙摩托车最终弯道取胜。"]],
	"ark_ling": ['female', 'yan', "3/4", ["ark_liuyun", "ark_dengtian"], []],
	"ark_taifu": ["male", "yan", 4, ["ark_zhilve", "ark_boya"], []],
	//		"ark_jiuselu": ['female', 'yan', 3, ['ark_cibei', 'ark_pudu'], []],
	"ark_laoli": ['male', 'yan', 4, ['ark_tianyan', 'ark_dongxin'], []],
	"ark_shitieshou": ['female', 'yan', 4, ['ark_gongfu', 'ark_diqi'], []],
	//		"ark_chen": ['female', 'yan', 4, ['ark_hechi', 'ark_Cjueying'], []],
	//		"ark_liangxun": ["male", "yan", 4, ["ark_kaiji", "ark_jinming", "ark_hongwang"], []],
	//		"ark_ningciqiu": ["female", "yan", 3, ["ark_tongyun", "ark_diting"], []],
	"ark_baidingshan": ["male", "yan", 3, ["ark_xiuyou", "ark_mingpo", "ark_leizun"], ["hiddenSkill"]],
	"ark_zuole": ["male", "yan", 4, ["ark_shanduan", "ark_chengjian"], []],
	"ark_shenlou": ["male", "yan", 4, ["ark_cangxun", "ark_hanshui"], ["hiddenSkill"]],
	"ark_wuyou": ["male", "yan", 4, ["ark_jianfan", "ark_yinying"], []],
	"ark_sangshen": ['female', 'yan', 3, ['ark_caihao', 'ark_zengyun'], []],
	"ark_nian": ["female", "yan", 4, ["ark_jianghun", "ark_wanlie"], []],
	"ark_xi": ["female", "yan", 3, ["ark_zhanbi", "ark_mojin"], []],
	"ark_zhongyue": ["male", "yan", 4, ["ark_hanyue", "ark_paichao"], []],
	//卡兹戴尔	
	"ark_teleixisi": ["male", "kazidaier", 4, ["ark_yinyi", "ark_huinu", "ark_guzun"], ["zhu"]],
	"ark_teleixiya": ["female", "kazidaier", 4, ["ark_xingdeng", "ark_xinhuo", "ark_xiyang"], ["zhu", "des:<li>【基础信息】<br>技能设计：饼、无冕黎明、琉璃菠萝<br>角色配音：无<br>称号：<font color=#FFE66F>芳卉皇冕</font><br>姓名：特蕾西娅<br><br><li>【能力数据】<br>身份定位：主公<br>能力定位：过牌、辅助<br><br><li>【背景故事】<br></br>被篡位的前卡兹戴尔统治者，“巴别塔”组织成员之一，萨卡兹人。为人亲和，意志坚定，深受萨卡兹人民的尊敬，但在一次斩首行动中被杀害。目前遗体已被赦罪师“复活”，拥有自主意识，知道自己已死复活的事实，但自我感情被抑制，实际已成为全体萨卡兹愤怒和悲伤的容器。"]],
	"ark_manfuleide": ["male", "kazidaier", 4, ["ark_jingli", "ark_zhiti"], []],
	"ark_shanling": ["female", "kazidaier", 4, ["ark_shezui", "ark_chenhun"], []],
	"ark_yeying": ["female", "kazidaier", 3, ["ark_jingyou", "ark_wange"], []],
	"ark_bxzk": ["none", "kazidaier", "1/6", ["ark_jiqun", "ark_touxi"], []],
	"ark_xmk": ["male", "kazidaier", 4, ["ark_guimai", "ark_xueyu"], []],
	"ark_sfzk": ["male", "kazidaier", "3/4", ["ark_danxiu", "ark_fuying"], []],
	"ark_yineisi": ["female", "kazidaier", 4, ["ark_guanxin", "ark_tongming"], ["des:<li>【基础信息】<br>技能设计：无冕黎明、琉璃菠萝<br>角色配音：无<br>称号：<span style=color:rgba(180,180,180,0.8); >心芒影重</span><br>姓名：伊内丝<br><br><li>【能力数据】<br>身份定位：反贼，忠臣<br>能力定位：控场<br><br><li>【背景故事】<br></br>某萨卡兹佣兵队队长之一，但种族并非萨卡兹，与赫德雷同队。源石技艺可观察他人“阴影”，进而感知其内心。虽与W多起小争执，但对其心存信任。卡兹戴尔内战结束后以雇佣兵身份加入整合运动。在切尔诺伯格时听从Scout的建议，用源石技艺察觉到了塔露拉的变化，但在前往转告W的途中被多名整合运动士兵围攻，伪装了自己的死亡。"]],
	"ark_hedelei": ["male", "kazidaier", 4, ["ark_shenlve", "ark_siqian"], []],
	//谢拉格
	"ark_yela": ["female", "xielage", 4, ["ark_dimei", "ark_cifu"], []],
	"ark_yaxin": ["female", "xielage", 3, ["ark_dengya", "ark_tianya"], []],
	"ark_yinhui": ["male", "xielage", 4, ["ark_taolve", "ark_tianmu", "ark_ceyi"], ["zhu"]],
	"ark_chuxue": ["female", "xielage", 3, ["ark_huixiang", "ark_tianwei"], []],
	"ark_nuoxisi": ["male", "xielage", 3, ["ark_cuiyu", "ark_chimie"], []],
	"ark_aketuosi": ["male", "xielage", 5, ["ark_mangjin", "ark_fenzheng"], []],
	"ark_jian": ["female", "xielage", 6, ["ark_dangmi", "ark_weijin"], []],
	"ark_walaisi": ["female", "xielage", 4, ["ark_qingyue", "ark_jinzhong"], []],
	"ark_guluo": ["male", "xielage", 4, ["ark_mangye", "ark_cushuai"], []],
	"ark_latatuosi": ["female", "xielage", 3, ["ark_jiandu", "ark_jvfen"], []],
	"ark_xiulusi": ["female", "xielage", 3, ["ark_yanyan", "ark_Xjiaojiao"], []],
	"ark_youkatan": ["male", "xielage", 4, ["ark_zhengzheng", "ark_Yjiaojiao"], []],
	"ark_dazhanglao": ["male", "xielage", 4, ["ark_wanzheng", "ark_zhenliang", "ark_shuquan"], []],
	"ark_moxi": ["female", "xielage", 3, ["ark_molu", "ark_xiaoxiang"], []],
	"ark_jiguang": ["female", "xielage", 4, ["ark_chenmian", "ark_baobao"], []],
	"ark_qiesite": ["male", "xielage", 4, ["ark_fubi", "ark_shubian"], []],
	//逐火英桀
	"ark_meibiwusi": ["female", "geju", 3, ["ark_zhongshi", "ark_shetui"], ["des:？"]],
	"ark_weierwei": ["female", "geju", "3/8", ["ark_zhongbai", "ark_zhizhen", "ark_dianmo"], ["des:？"]],
	//	"ark_geleixiu": ["female", "geju", 3, ["ark_xingye", "ark_xincai"], ["des:？"]],
	//	"ark_ailixiya":["female","geju",4,["ark_zhiai","ark_Ezhizhen"],["des:？"]],
	//	"ark_aboniya": ["female", "geju", 3, ["ark_jielv", "ark_qingshu"], ["des:？"]],
	//	"ark_yidian": ["female", "geju", 3, ["ark_songshi", "ark_fuge"], []],
};
