export const characterTitle = {
	ark_kafuka: '<font color=#228B22>炫惑魔方</font>',
	ark_tuola: '逐夜的大汗',
	ark_jici: '<font color=#FFFF00>至高之术',


	ark_helage: '<font color=#FFAF60>血峰残月',
	ark_sikadi: '浊心',
	ark_shenhaise: '<font color=guree>聚瀚凝蜃',
	ark_nengtianshi: '<font color=red>负翼执武',
	ark_zongxia: '<font color=white>绽放的奇迹',
	ark_linglan: '幽焰火狐',
	ark_shuangxing: '<font color=#D9FFFF>炽恸冬痕',
	ark_shijunzhe: '<font color=#8B0000>行莫移尘',
	ark_leide: '<font color=#FF3030>赤领鬼',
	ark_shanling: '<font color=#6f757b>缁黯渺黎',
	ark_yeying: '<font color=#FFF8D7>纯白碎梦',
	ark_lindong: '<font color=#808000>冬将军',

	//		ark_laoli:"<font color=#FFFF37>凶吉莫问",
	ark_yifulite: '<font color=red>炎魔共主',
	ark_sly: '坚城铁律',
	ark_teleixisi: '<font color=#6a4f4e>血荆王座',
	ark_teleixiya: '<font color=#FFE66F>芳卉皇冕',
	ark_manfuleide: '<font color=#FFBB77>赴烈不归',
	ark_bxzk: '<font color=green>流漫陆离',
	ark_xmk: '<font color=red>粲世红莲',
	ark_sfzk: '<font color=black>死生枯荣',
	ark_meifeisite: '<font color=#600030>恶魔之吻',
	ark_gezhe: '<font color=#FBFBFF>美丽的生灵',
	ark_aiguozhe: '<font color=#623128>不败战神',
	ark_yisang: '<font color=grey>蜷隐喧市',
	ark_Amy: '<font color=#1E90FF>至善魔王',
	ark_fushide: '<font color=#DDDDFF>幻影弩手',
	ark_jiu: '<font color=#9DEF1F>陌上花开',
	ark_hong: '<font color=red>秉烛夜游',
	ark_shuiyue: '反移情之幻',
	ark_huihou: '织雨巡晴',
	ark_keebo: '<font color=#808000>长路独行',
	ark_senran: '蒸汽之心',
	ark_talula: '<font color=#DE4A4C>焰向光明',
	ark_alina: '<font color=#FF5A5A>烁启长夜',
	ark_suigu: '<font color=#EEAD0E>引恨双生',
	ark_wulian: '咒厄低语',
	ark_miuersaisi: '<font color=#66B3FF>幻海</font><font color=#9DEF1F>潮升</font>',
	ark_duanzuizhe: '<font color=#e3fb46>罪火张天',
	ark_hanmierdun: '抱负恣睢',
	ark_doctor: '<font color=#555760>巴别塔之恶灵',
	ark_dadi: '乱世巨星',
	ark_shierteer: '<font color=red>末日黄昏',

	ark_chengshan: '<font color=pink>梦想火花',
	ark_yeyan: "<font color=#708090>轻步淡渐",
	ark_hemo: '<font color=#228B22>斑羽飘布',
	ark_Ptilopsis: '<font color=#E6E6FA>二象折跃',
	ark_huoerhaiya: '<font color=#32CD32>碧羽凌霄',

	ark_Niyan: '<font color=#A7913D>秽壤终裔',
	ark_fengdi: '<font color=orange>可攻城厦',
	ark_Saileach: '<font color=yellow>荣辉之帜',
	ark_haojiao: '<font color=orange>役血砥锋',
	ark_tianhuo: '<font color=#FF5A5A>炽盛光芒',
	ark_weifeng: '<font color=#FF7F00>旧章新曲',
	ark_bolv: '<font color=#00EC00>轻岚渡岭',

	ark_furong: '<font color=cyan>濯尘愈心',
	ark_yanrong: '<font color=red>焰淬狱火',
	ark_kuiying: '<font color=red>镜中虚影',
	ark_moyao: '<font color=#2BD654>固本活新',
	ark_sikadi_blue: '<font color=blue>涌潮悲歌',
	ark_tiaoxiangshi: '<font color=#9DEF1F>庭染秾芳',
	ark_meilansha: '<font color=#1E90FF>西风之信',
	ark_huoshen: '<font color=orange>匠心独运',
	ark_luoxiaohei: '<font color=#000000>云烁身捷',

	ark_meier: '<font color=#C48888>独木成林',
	ark_duoluoxi: '<font color=#9DEF1F>绿野幻梦',
	ark_paerweisi: '<font color=#228B22>波谲云诡',
	ark_feierdinan: '<span style=color:rgba(0,101,255,0.7); >孤星擎夜</span>',
	ark_: '星野驰寒',


	///拉特兰
	ark_saixiliya: '奈非天',
	ark_feiyameita: '<font color=red>炽焰无霾',
	ark_jiaozong: '<font color=#FFED97>光明乐园',
	ark_mositima: '<font color=#1E90FF>蚕输时域',
	///深池
	ark_mandela: '<font color=#00000>风信孤音',
	ark_ahemoni: '<font color=#10A552>秘焰深隐',
	ark_muxueshouwei: '<font color=balck>深影之怒',

	///罗德岛
	ark_kedao: '蹈中持律',
	ark_baoyu: '<font color=#98FB98>萧萧难鸣',
	ark_midiexiang: "<font color=#BBFFFF>万物一府",
	ark_hongdou: '一骑当千',
	ark_sharp: '砂原之怒',
	ark_touch: '月冕之圣',
	ark_stormeye: '暗风之血',
	ark_pith: '潮汐之贤',

	ark_ash: '<font color=red>迅<font color=#FFA500>登<font color=#40E0D0>之<font color=#9400D3>铳',
	ark_flashstrike: '<font color=red>炽<font color=#FFA500>穹<font color=#40E0D0>之<font color=#9400D3>卫',
	ark_chariot: '<font color=red>机<font color=#FFA500>枪<font color=#40E0D0>壁<font color=#9400D3>垒',
	ark_frost: '<font color=red>极<font color=#FFA500>北<font color=#40E0D0>之<font color=#9400D3>陷',
	///谢拉格
	ark_yela: '<font color=#4038ff>风雪欲来',
	ark_chuxue: "<font color=#1E90FF>霜威轶漠",
	ark_yaxin: "<font color=#40E0D0>人胜天高",
	ark_yinhui: "<font color=#6495ED>执隼击苍",
	ark_nuoxisi: "<font color=#00CED1>菀枯何如",
	ark_aketuosi: "<font color=#FF4500>遏北悍锋",
	ark_jian: "<font color=#EE9A00>三冠武王",
	ark_walaisi: "<font color=#CDAA7D>影隐翼伏",
	ark_guluo: "<font color=#CD4F39>疏略豪行",
	ark_latatuosi: "<font color=#EE9A49>浅见明思",
	ark_xiulusi: "<font color=#EE9A49>智明无邪",
	ark_youkatan: "<font color=#EE9A49>比翼连枝",
	ark_moxi: "<font color=#8A2BE2>无垠纤尘",
	ark_jiguang: "<font color=#24f5e5>极昼捕手",
	ark_dazhanglao: "<font color=#BEBEBE>不化磐石",
	ark_qiesite: "<font color=#40E0D0>殚心竭虑",
	///东国
	ark_cuoe: '明台非空',
	///叙拉古
	"ark_beinaerduo": "<font color=#8c5f60>殛海斫浪",
	"ark_aerbeituo": "<font color=#BEBEBE>竭黯辰焉",
	"ark_lapulande": "<font color=#BEBEBE>荒芜命途",
	"ark_xixili": "<font color=#DAA520>秩序之光",
	"ark_agenier": "<font color=#D3D3D3>此即秩序",
	"ark_qiaowanna": "<font color=#f8f23f>出湍离尘",
	"ark_walahe": "<font color=#742526>沸温难凉",
	"ark_wen": "<font color=#8c5f60>沉疴噤声",
	"ark_danbulang": "<font color=#8c5f60>泞沦腥雨",
	"ark_ziyue": "<font color=#8c5f60>头狼獠牙",
	"ark_dekesasi": "<font color=#0000CD>斩荆碎路",

	///哥伦比亚
	ark_xingji: '<span style=color:rgba(0,255,255,0.8); >焉有火光</span>',
	ark_shan: '<font color=#708090>巍峨崇峻',
	ark_gumi: '<font color=orange>棼霭炊香',

	///萨尔贡
	ark_mila: '<font color=#FFF68F>砂中莹璞',
	///玻璃瓦尔
	ark_longshelan: '<span style=color:rgb(255,231,0); >剑走偏锋</span>',
	///伊比利亚	
	ark_amaya: "<span style=color:rgba(0,255,180,0.6); >永世星海</span>",
	ark_shendian: "<font color=#7D7DFF>深渊守望</font>",
	ark_ailini: "<span style=color:rgba(207,56,177,1); >挑灯看剑</span>",
	ark_yineisi: "<span style=color:rgba(180,180,180,0.8); >心芒影重</span>",
	ark_hedelei: "<font color=#A0522D>敛涛藏锋</font>",
	///大炎
	ark_wenyue: '<font color=#FF79BC>扶君之翼',
	ark_weiyanwu: '<font color=#EE2C2C>纵横恣肆',
	ark_jiuselu: '<font color=#faea99>吉兆显祥',
	ark_laoli: "<span style=color:rgb(255,231,0); >凶吉莫问</span>",
	ark_taifu: "<span style=color:rgba(180,180,180,0.8); >江山作裘</span>",
	ark_linyuxia: '<font color=#cd5ad8>阴渠秘灵',
	ark_baidingshan: '<font color=#66B3FF>青雷伯',
	ark_shenlou: '<font color=#66B3FF>浮萍雨师',
	ark_zuole: '<font color=#66B3FF>谋事在人',
	ark_liangxun: '<font color=#66B3FF>冬桃开知否',
	ark_ningciqiu: '<font color=#66B3FF>花语向枝头',
	ark_wuyou: '<font color=#66B3FF>檐下听雨',
	ark_sangshen: '<font color=#66B3FF>乾远春归',
	ark_zhongyue: '<font color=#FFD700>万象为宾',
	ark_nian: '<font color=#FF0000>天有洪炉',
	ark_xi: '<font color=#00CED1>星藏点雪',
	ark_ling: '<font color=#66B3FF>卿饮尘寰',
	//莱塔尼亚
	ark_getelude: '<font color=#708090>寤寐余音',
	ark_kanielian: '<font color=#FFF68F>餮噬残沙',
	ark_biegele: '<font color=#708090>滴滤涩香',
	//卡西米尔
	ark_yanwei: '<font color=red>赤焰松灵',
	ark_YQSlinguang: '<font color=#FFFF00>初升艳阳',
	ark_baijin: '<font color=#FFFFE0>弦上行路',
	ark_xiaguang: '<font color=#FFFF00>炳若日星',
	ark_bianren: '<font color=#FFFF00>霁月光风',
	ark_maenna: '<font color=#708090>潜光隐耀',
	ark_yezong: '永矢弗谖',
	ark_yuanya: '<font color=#FFFF37>伴风秋声',
	ark_huihao: '权变筹捷',
	ark_jiemi: '丹心碧血',
	ark_monike: '<font color=#00CED1>夕惕朝乾',
	ark_luoyi: '<font color=#1E90FF>不立危墙',
	ark_fugewaerde: '飞鹰走马',
	ark_mading: '铁马埋戈',
	ark_kewaer: '守暗待明',
	ark_fubaiDiaoling: '涸辙腐草',
	ark_mobu: '伶牙俐齿',
	ark_maiji: '处官言权',
	ark_seqiyake: '篱壁困兽',
	ark_taitesiBaiyang: '循故自封',
	ark_aoermoYinggela: '<font color=#778899>沐猴而冠',
	ark_qiaernei: '幕台傀偶',
	ark_makeweici: '<font color=#FFFFFF>相须而行',
	ark_laimu: '银枪天马',
	ark_tuolanKashi: '<font color=#778899>济济于世',
	ark_luosu: '<font color=#FFD700>持筹握算',
	ark_weiweianna: '<font color=#FFF8D7>星星点灯',
	ark_Decapolis: '<font color=red>血祭血神',
	ark_gelani: '<font color=cyan>骓踏苍溪',
	ark_qiesibo: '<font color=#D0D0D0>举目破败',
	ark_daisite: '<font color=yellow>丹书铁契',
	//逐火英桀
	ark_meibiwusi: "<font color=green>无限·噬界之蛇",
	ark_weierwei: "<font color=#708090>螺旋·愚戏之匣",
	ark_geleixiu: "<font color=#1E90FF>繁星·绘世之卷",
	ark_ailixiya: "<font color=pink>真我·人之律者",
	ark_aboniya: "<font color=#d6cb00>戒律·深罪之槛",
	"ark_yidian": "<font color=#FFFF00>黄金·璀耀之歌",

}